### ISSUE TITLE
Dw1560 big sur

### ISSUE THREAD

**Issue by diepnt90** [findyy99/ThinkPad-T450S-Hackintosh-macOS-Big-Sur#2]
Hi,

I'm using X1 carbon gen 4 and Dw1560. Could you please tell me how to make dw1560 working for Big Sur?

I see you are using dw1560 and have wifi working

Thank you.

**Comment by findyy99** [comment]
Because the update of Big Sur and `AriportBcrmFixup.kext`, I only can tell you how to drive the DW1560 on the version in my repository. And Big Sur beta2 was tested OK.
- Download the kext from my repository, add it to EFI and edit the `config.plist`.
- add  `brcmfx-driver=2 -brcmfxbeta` to `NVRAM/7C436110-AB2A-4BBB-A880-FE41995C9F82/boot-args` in opencore config.plist
- add `booter-fileset-basesystem`,`booter-fileset-kernel` to `NVRAM/7C436110-AB2A-4BBB-A880-FE41995C9F82`, both of them should be set to `00(data)`
- Restart the computer, if the still not work, see my readme to check the nvram has been changed. If the nvram has not been changed, you can try reset nvram using the `opencore` utility.

**Comment by DJohnston79** [comment]
I have this same issue only using open core. I have two ssds ,. One with an restored image of big sur beta 2 and on which I use clover ...everything on this works.  

the other had beta 3 I installed from USB and OC. The wifi icon is there and in network it won't let.me turn it on. It just says turned off.

**Comment by findyy99** [comment]
@BigD1979666  try the newest commit of the repository, I have tested on beta3!

**Comment by DJohnston79** [comment]
@findyy99 I will. Where do you pull your builds from? I know the oc guide has links to builds but should I go for general release or nightly?

**Comment by diepnt90** [comment]
@findyy99 Thank you so much. I have tried https://medium.com/@andv/making-wifi-on-big-sur-unsupported-macs-with-failed-with-66-error-36c98e3f7965 and it works.

Another issue is that i could not use F1,2,3 and F4,5 for sound/bright control. It worked well with Catalina. Do you have any idea? I need to update APCI files?

**Comment by findyy99** [comment]
@diepnt90 I think Mayne your APCI files doesn't load correctly. You can use `log show --last boot | grep -Ei "ACPI"` in terminal to check if there are errors when load the APCI files. And this is a [blog](https://blog.skk.moe/post/ssdt-map-fn-shortcuts/) about custom the `Fn` keys, but it is in Chinese, hope it will help you!

**Comment by findyy99** [comment]
@BigD1979666 Good news! OC 0.6.0 release has been released serval hours ago, And I used to build it by this [tool](https://github.com/Pavo-IM/ocbuilder)

**Comment by diepnt90** [comment]
Thank you @findyy99
